AWSTemplateFormatVersion: "2010-09-09"
Description: Base AWS EC2 Instance - AMI
Resources:
  MyEC2Instance: #An inline comment
    Type: AWS::EC2::Instance
    Properties: 
      AvailabilityZone : us-east-2c
      ImageId: ami-38c
      InstanceType: t2.micro
#      SubnetId: subnet-e6c9c5ac
      SecurityGroups:
         - rk-security-grp  
      Tags:
          - Key: Name
            Value: dev5-cloudformation  
      KeyName: Poc-A-staging-Dev-6-key
      BlockDeviceMappings:
         -
           DeviceName: /dev/xvda
           Ebs:
             VolumeType: gp2
             VolumeSize: 8



