- name: test raw module
  hosts: all
  tasks:
    - name : "test scheduled task"
      win_scheduled_task: 
        name="TaskName" 
        execute="cmd" 
        frequency="daily" 
        time="9am" 
        description="open command prompt" 
        path="example" 
        enable=yes 
        state=present 
        user=SYSTEM
